import exception3

print(exception3.add(2, 9))
print(exception3.sub(2, 9))
print(exception3.mul(2, 9))

